# Trading Parameters
trading:
  symbol: ALGOUSDC
  grid_size: 6  # Fewer levels for more focused trading
  grid_spacing: 0.02  # 2% between levels for wider range
  position_size: 0.2  # Larger positions for meaningful profits
  max_positions: 3
  min_profit_usd: 0.5

# Risk Management
risk:
  stop_loss: 0.02  # 2% stop loss
  take_profit: 0.01  # 1% take profit
  max_drawdown: 0.05  # 5% maximum drawdown
  position_timeout: 3600  # 1 hour timeout

# Technical Indicators
indicators:
  # RSI Settings - more lenient
  rsi_period: 14
  rsi_oversold: 40  # More aggressive buy trigger
  rsi_overbought: 60  # More aggressive sell trigger
  
  # Volume Profile
  volume_periods: 20
  min_volume_threshold: 100  # Reduced for more trades

# Binance Settings
binance:
  testnet: true
  use_bnb_fees: false
  
# Backtesting Settings
backtest:
  initial_capital: 10000
  test_period_days: 30
  include_weekends: true
  fee_model: "binance"
  slippage_model: "fixed"