# Trading Parameters
trading:
  symbol: ALGOUSDC
  grid_size: 6  # Number of grid levels
  grid_spacing: 0.02  # 2% between levels
  position_size: 0.2  # Position size as fraction of capital
  max_positions: 3
  min_profit_usd: 0.5
  sampling_period: 27  # Wolfpack sampling period
  range_multiplier: 1.0  # Wolfpack range multiplier

# Risk Management
risk:
  stop_loss: 0.02  # 2% stop loss
  take_profit: 0.01  # 1% take profit
  max_drawdown: 0.05  # 5% maximum drawdown
  position_timeout: 3600  # 1 hour timeout
  min_success_rate: 0.4  # 40% minimum success rate for grid levels
  min_hold_time: 30  # 30 minutes minimum hold time

# Technical Parameters
technical:
  rsi_period: 14  # RSI calculation period
  short_trend_period: 3  # Short-term trend period
  medium_trend_period: 6  # Medium-term trend period
  min_volatility: 0.005  # 0.5% minimum volatility
  max_volatility: 0.03  # 3% maximum volatility
  rsi_oversold: 40  # RSI oversold level
  rsi_overbought: 60  # RSI overbought level
  trend_strength: 2  # Required trend count
  use_emas: false  # Enable EMAs
  ema1_period: 21  # Fast EMA
  ema2_period: 50  # Medium EMA
  ema3_period: 200  # Slow EMA
  use_bb: false  # Enable Bollinger Bands
  bb_period: 20  # BB period
  bb_std: 2.0  # Standard deviation multiplier

# Exchange Settings
binance:
  testnet: true  # Use testnet
  use_bnb_fees: false  # Use BNB for fees
  
# Backtesting Settings
backtest:
  initial_capital: 10000  # Starting capital in USDC
  test_period_days: 30  # Backtest duration
  timeframe: "1h"  # Trading timeframe